name: TGJU Bot

on:
  schedule:
    # هر 2 ساعت (UTC)
    # 09:00 تا 16:00 ایران ≈ 05:30 تا 12:30 UTC
    - cron: "30 5 * * *"
    - cron: "30 7 * * *"
    - cron: "30 9 * * *"
    - cron: "30 11 * * *"
    - cron: "30 13 * * *"
    - cron: "30 15 * * *"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
